# ==========================================
# recommendation.py
# ==========================================

import pickle
import numpy as np

from sklearn.metrics.pairwise import cosine_similarity

from config import (
    TOP_K,
    METADATA_FILE,
    BASELINE_EMBEDDING_FILE,
    FINETUNED_EMBEDDING_FILE,
    SIAMESE_EMBEDDING_FILE,
)
from preprocess import preprocess_image
from feature_extractor import load_feature_extractor, extract_embedding

# ==========================================
# Shared metadata (same order for all 3 models)
# ==========================================

with open(METADATA_FILE, "rb") as f:
    metadata = pickle.load(f)

EMBEDDING_FILES = {
    "baseline": BASELINE_EMBEDDING_FILE,
    "finetuned": FINETUNED_EMBEDDING_FILE,
    "siamese": SIAMESE_EMBEDDING_FILE,
}

# ==========================================
# Cache loaded models + embeddings so repeated
# calls (e.g. from Streamlit) don't reload from
# disk every single time.
# ==========================================

_model_cache = {}
_embedding_cache = {}


def _get_model(model_type):
    if model_type not in _model_cache:
        _model_cache[model_type] = load_feature_extractor(model_type=model_type)
    return _model_cache[model_type]


def _get_embeddings(model_type):
    if model_type not in _embedding_cache:
        _embedding_cache[model_type] = np.load(EMBEDDING_FILES[model_type])
    return _embedding_cache[model_type]


def recommend_products(image_path, model_type="finetuned", top_k=TOP_K):
    """
    Recommend visually similar products.

    Parameters
    ----------
    image_path : str
        Path to the query image.
    model_type : str
        "baseline" | "finetuned" | "siamese" — which embedding
        space to search in. Must match one of the three
        generated by generate_embeddings.py.
    top_k : int
        Number of results to return.
    """

    if model_type not in EMBEDDING_FILES:
        raise ValueError(
            f"model_type must be one of {list(EMBEDDING_FILES.keys())}"
        )

    model = _get_model(model_type)
    embeddings = _get_embeddings(model_type)

    image = preprocess_image(image_path)
    query_embedding = extract_embedding(model, image)

    similarity = cosine_similarity([query_embedding], embeddings)[0]

    indices = np.argsort(similarity)[::-1][:top_k]

    recommendations = []

    for idx in indices:
        recommendations.append({
            "score": float(similarity[idx]),
            "id": metadata[idx]["id"],
            "image_path": metadata[idx]["image_path"],
            "articleType": metadata[idx]["articleType"],
            "gender": metadata[idx]["gender"],
        })

    return recommendations